### ISSUE TITLE
License Restrictions?

### ISSUE THREAD

**Issue by sidsingla** [kennyvoo/face-occlusion-generation#10]
Hi,
Is there a License Restrictions on the dataset? Could it be used for commercial purposes?

**Comment by kennyvoo** [comment]
Hi @sidsingla, I've listed down the license of the datasets used in this paper.


The license for the RealOcc and RealOcc-Wild: (Free to use)
https://www.pexels.com/license/
https://unsplash.com/license

The license for 11k Hands: (MIT) 
https://github.com/mahmoudnafifi/11K-Hands/blob/master/LICENSE.md

The license for DTD dataset: (Unknown)
https://www.robots.ox.ac.uk/~vgg/data/dtd/
but their images are from google and flikr

The license for CelebAMaskHQ: (for non-commercial research purposes only.)
https://github.com/switchablenorms/CelebAMask-HQ

The license for COCO dataset: [Creative Commons Attribution 4.0 License](https://creativecommons.org/licenses/by/4.0/legalcode)
https://cocodataset.org/#termsofuse
