### ISSUE TITLE
About the unobstructed part

### ISSUE THREAD

**Issue by lkrhhh** [kennyvoo/face-occlusion-generation#11]
Hello, sir. Congratulations on your success. I have some questions to ask. It refers to whether you can change some codes to generate occlusion without changing the original image. Because some pictures will lighten the color of the un occluded part after being occluded. Thank you for your answer

**Comment by kennyvoo** [comment]
Hi, you can comment out the `RandomBrightnessContrast` augmentation in this [function](https://github.com/kennyvoo/face-occlusion-generation/blob/main/utils/utils.py#L43). can comment `AdvancedBlur` as well if you doesn't want any augmentation
