### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Jaep0805** [kennyvoo/face-occlusion-generation#14]
Hi, 
could you please provide a pretrained model of segformer or any other tested model?

thank you

**Comment by kennyvoo** [comment]
@Jaep0805 here you go
https://drive.google.com/drive/folders/14zvOX3tIaNrM0CgGSSMEfkHrOh3slxsS?usp=sharing

**Comment by Jaep0805** [comment]
Thanks a lot!

**Comment by kennyvoo** [comment]
@Jaep0805 I realized the pretrained weights are not provided, I'll ping you if I uploaded it.

**Comment by kennyvoo** [comment]
@Jaep0805 [pretrained_weight](https://1024terabox.com/s/15Y9yuyeEouyWM9X27GoAzQ)
