### ISSUE TITLE
Request for Model checkpoint

### ISSUE THREAD

**Issue by mittalgovind** [kennyvoo/face-occlusion-generation#5]
Hello, 

Great work and congratulations on getting accepted to CVPRW. 

I wanted to request you the trained model checkpoints of DeepLabV3, etc. If you could share that would be amazing as I am trying to get one my project working and your work got me really excited. 

Thanks.

**Comment by lkrhhh** [comment]
Can I ask you some questions。When l generate the occlusion ,The masks are all black

**Comment by kennyvoo** [comment]
> Great work and congratulations on getting accepted to CVPRW.
> 
> I wanted to request you the trained model checkpoints of DeepLabV3, etc. If you could share that would be amazing as I am trying to get one my project working and your work got me really excited.
> 
> Thanks.

I can share one of the weights and config. I'll release the rest soon.
https://drive.google.com/drive/folders/12SGCl0tjf_M2Oqb7JfSZzz57PVli4QQh?usp=sharing

**Comment by kennyvoo** [comment]
> Can I ask you some questions。When l generate the occlusion ,The masks are all black Thank you

You can remove the `/255` at [here](https://github.com/kennyvoo/face-occlusion-generation/blob/main/main.py#L120) to generate the mask between (0,255).

If you already generated the mask, can use the following code to change the mask to (0,255)
``` python
import os
import cv2
import multiproces
input_path="./mask/"
output_path= "./output/"
for file in os.listdir(input_path):
    img=cv2.imread(input_path+file)
    cv2.imwrite(output_path+file,img*255)
```

**Comment by lkrhhh** [comment]
Hello sir
Is my great honor to see your artical.&nbsp;


As a freshman of master's degree, I need to generate an occlusion data set. Your article has helped me a lot. But now I encounter some problems. When I generate occlusion on faces, I find that some faces turn into the opposite direction in the generated image, such as left to right. How to solve this problem? Can you give me some suggestions. Thank you for your answer, and I wish you every success in your work.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kennyvoo/face-occlusion-generation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 晚上9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kennyvoo/face-occlusion-generation] Request for Model checkpoint (Issue #5)





  
Can I ask you some questions。When l generate the occlusion ,The masks are all black Thank you
  
You can remove the /255 at here to generate the mask between (0,255).
 
If you already generated the mask, can use the following code to change the mask to (0,255)
 import os import cv2 import multiproces input_path="./mask/" output_path= "./output/" for file in os.listdir(input_path):     img=cv2.imread(input_path+file)     cv2.imwrite(output_path+file,img*255)

**Comment by kennyvoo** [comment]
> Hello sir Is my great honor to see your artical.&nbsp; As a freshman of master's degree, I need to generate an occlusion data set. Your article has helped me a lot. But now I encounter some problems. When I generate occlusion on faces, I find that some faces turn into the opposite direction in the generated image, such as left to right. How to solve this problem? Can you give me some suggestions. Thank you for your answer, and I wish you every success in your work.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kennyvoo/face-occlusion-generation" ***@***.***&gt;; 发送时间:&nbsp;2022年6月29日(星期三) 晚上9:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [kennyvoo/face-occlusion-generation] Request for Model checkpoint (Issue #5) Can I ask you some questions。When l generate the occlusion ,The masks are all black Thank you You can remove the /255 at here to generate the mask between (0,255). If you already generated the mask, can use the following code to change the mask to (0,255) import os import cv2 import multiproces input_path="./mask/" output_path= "./output/" for file in os.listdir(input_path): img=cv2.imread(input_path+file) cv2.imwrite(output_path+file,img*255) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

The mask will flipped together with the face. But if you don't want the faces to flip horizontally, just comment out this [line](https://github.com/kennyvoo/face-occlusion-generation/blob/main/utils/utils.py#L48).
