### ISSUE TITLE
model reproduction question

### ISSUE THREAD

**Issue by jinwonkim93** [kennyvoo/face-occlusion-generation#6]
Hi thanks for the great work about occlusion-aware augmentation method.

is there a plan for sharing training code or a pretrained weight of models (segformer) in the paper?

**Comment by kennyvoo** [comment]
@jinwonkim93 I'll release it probably latest by mid August. The model was trained on [mmsegmentation](https://github.com/open-mmlab/mmsegmentation). if you need, I can share the configs and required files to train the model.

**Comment by jinwonkim93** [comment]
@kennyvoo yes It would be very thankful if you share configs and files.

**Comment by jinwonkim93** [comment]
@kennyvoo could share a link for configs and required files?

**Comment by kennyvoo** [comment]
@jinwonkim93 I'll upload by weekend.

**Comment by kennyvoo** [comment]
Here you go. @jinwonkim93 
https://drive.google.com/drive/folders/14zvOX3tIaNrM0CgGSSMEfkHrOh3slxsS?usp=sharing

**Comment by jinwonkim93** [comment]
@kennyvoo  Thanks for the configs.
![image](https://user-images.githubusercontent.com/26476095/180698921-07a4072c-c2f6-47dd-b5ae-6619d07b3cb1.png)
Have you ever encounter this problem?

**Comment by kennyvoo** [comment]
No. I never encounter this issue before.

**Comment by jinwonkim93** [comment]
oh thanks for the fast reply. I will ask mmseg issue.
