### ISSUE TITLE
contributing this dataset to mmsegmentation

### ISSUE THREAD

**Issue by jinwonkim93** [kennyvoo/face-occlusion-generation#7]
Hi, is it okay to PR this dataset to mmsegmentation?

I have been using this dataset since you publish the paper and it is very helpful to my projects.

I think it would be nice if  mmsegmentation supports this dataset

**Comment by kennyvoo** [comment]
> Hi, is it okay to PR this dataset to mmsegmentation?
> 
> 
> 
> I have been using this dataset since you publish the paper and it is very helpful to my projects.
> 
> 
> 
> I think it would be nice if  mmsegmentation supports this dataset

Sure.

**Comment by kennyvoo** [comment]
Let me know if you need any help.

**Comment by jinwonkim93** [comment]
@kennyvoo  
https://github.com/open-mmlab/mmsegmentation/pull/2194 
successfully merged on mmsegmentation.
